main: com.github.redshirt53072.dimmanager.general.DimManager
name: DimManager
author: redshirt72
version: "0.1.0"
api-version: "1.17"
softdepend: [GrowthBaseApi]
commands:
  world: 
    description: world tp command
    usage: "/world <world name>"
    aliases: world
    permission: dim.normal
  alldim:
    description: all dimension tp command
    usage: "/alldim <dim name>"
    aliases: alldim
    permission: dim.normal
permissions:
  dim.normal:
    description: normal player
    default: true
  dim.op:
    description: op player
    default: op
  dim.*:
    description: commands
    children:
      dim.normal: true
      dim.op: true